name: Build Docker image and push

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "Build environment, effects image tag prefix."
        type: string

      runs-on:
        required: false
        description: 'Platform to execute on. Default ["self-hosted", "cere-network-large"]'
        type: string
        default: '["self-hosted", "cere-network-large"]'

      file:
        required: false
        description: "Path to the Dockerfile. Default: ./Dockerfile"
        type: string
        default: './Dockerfile'

      context:
        required: false
        description: "Build's context. Defaults ./"
        type: string
        default: './'

      repository:
        required: false
        description: "Image repository. Defaults to github repository name."
        type: string
        default: ${{ github.event.repository.name }}

      configure_host_command:
        required: false
        description: "Additional command to configure host"
        type: string
        default: ''

      build-args:
        required: false
        description: "Additional build arguments for docker build"
        type: string
        default: |
          ENV_FILE_NAME=${{ inputs.environment }}

    secrets:
      NPM_TOKEN:
        required: false
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  deploy-to-dokerhub:
    name: Build docker image, push to dockerhub.
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure host
        if: ${{ inputs.configure_host_command != '' }}
        run: ${{ inputs.configure_host_command }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Process version
        id: version
        run: |
          echo "image_tag=${{ inputs.environment }}-${{ github.run_attempt}}-$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Build and push docker image to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
          no-cache: true
          platforms	: |
            linux/amd64
            linux/arm64
          build-args: ${{ inputs.build-args }}
          tags: |
            cerebellumnetwork/${{ inputs.repository }}:${{ env.image_tag }}

    outputs:
      version: ${{ env.image_tag }}